# Supported funding platforms for this project

github: topalemirfaruk
# Eğer başka platform kullanırsan buraya ekleyebilirsin
# patreon: kullaniciadi
# open_collective: kullaniciadi
# ko_fi: kullaniciadi
# buy_me_a_coffee: kullaniciadi
# custom: ["https://www.paypal.me/topalemirfaruk"]
